language: generic
env:
  global:
  - AWS_REGION=ap-southeast-2
  - AWS_DEFAULT_REGION=ap-southeast-2

sudo: required

before_install:
  - echo "Installing AWS CLI"
  - pip install --upgrade --user awscli

script:
  - echo "Deploying"
  - aws cloudformation update-stack --stack-name vpc-test --template-body file://vpc.yaml || echo "Unable to update stack"

after_success:
  - bundle install
  - bundle exec rake spec

