language: generic
env:
  global:
    - AWS_REGION=ap-southeast-2
sudo: required
deploy:
  provider: script
  script: bash .pipeline/deploy.sh
  on:
    branch: master
  region: ap-southeast-2
  secret-access-key:
    secure: 07yP2k2Z1+eBVvrzSD7dQCmdMlOWvyaqYJ5jExEH3tM9H45itCSXTkN5TGVWtvOtdT/y5Xr6WYRhJfljZMYccoXfasjZh6N9YagpNy0IC6wnSJLjAEg/H4jgpEyeX8hhjpOXhLcpuWHkyy7XEBMP1ztyc0He14bU1/lJo423rGKMTIawq2fncPwVR3B3KGmGp/RGgchCY2qs73GPO0smAq5u9jhFvlqJV4V2Jpa2KCkWtPQhX3h1D+i9yXhC9lTpB7zl8L8AHNju5TgDS+Vw6HRc3dYYcD+yg3HHDLMLqbp9Io/CYK+hVhIm16OzBmry3o7E0ZeJAGHArkjHdYNc3DxPq1bqi2SaTR9veGbP0fiOwkyi3+OF9zq8LXpGYjxHq5sChrKTWqf0OJ9LVzeDfYG1gTORuHzihX6oWHlIM+rLfLmxanISb+QXBZ03hyDkw0bRH14tcUsRHcB20DnHRO+4d0L/sNWEweIUWpqRbmPHlT0BHUFaFyQ6LIKs4Ow1iFZasB7Rmz5B0nxK/CWCthQ2p1+q0D3qWpUSFqGjG8cCwOogy/ubeYLgVGLXm3uPmH0WwNcvrj1tt1qEbTQbQiKRzazJZaUD7/i055JosjsvDGVIM/BI1ygixo+hKsE4lIxslmuhZTbO8wQsC+b0jhJLLAesyoAFLhG/j8K76ak=
  access-key-id:
    secure: fYatMwyFKJNbwBP8Ggscj5PtO5T8NTfqyjcOrhNbON7I32mDq02rtA0ETxBYxN8wvbBeV0BwTYWda31GbyMzGr4D/3F7MA/XsXW/gER2ygMTVRea0XUXIBlf/1E5hCoEaBVThqQFsUlPqbv0T/7ukBoISUmjQKi5AuqC1jDqmvw8kbJs5f5xPFOo7iv4Kp6peR3j42oXzSh22E/3EQrjD5xDoIH79AJ5yUoQV9ESrEl0n4OtA699DoQTlN5Ax4+ni46AumKM+xk7x+eF/da7qqbN8GVXT3+Ys5HEPQldddYc1hQbvGVNi30m1dpk8xq4qFzAn4GnpNr9yniGbhc6i0W2U8UcSGGQ5kVUSYS9hTs+Y59FEbgZs4/sNiPzzRHgKAW8tPfGbuy93GQf2Mz3IECi/gWwLHg3Ah1HmTFmm1Ibgg3xsDoUlvRdaenNDqStDW8uek8MI/BRadJW68KYMO53+fN/gYFya2M2uQmpEUH7oqqxC5B4+iWsvYvyNI/TsVHx9DMLOUHIEXUlqwzbfMdwBhWgUS+sV+2AeTYXQ8w19pBYpQp4QXheRKqisrK6KQzbGBJwhKT9tk1yp6OElLcUWhC1COsDLwEUjFCfLTxRM7/qnHCN99EqsXlEfiVOMaGn1q5DfBzCG6xhSpn3zsS47uVNIfu1xCYHjlgsJFM=
after_deploy:
  - bundle install
  - bundle exec rake spec
  