language: generic
env:
  global:
  - AWS_REGION=ap-southeast-2

sudo: required

deploy:
  provider: script
  script: bash .pipeline/deploy.sh
  on:
    branch: master
  region: ap-southeast-2
after_deploy:
- bundle install
- bundle exec rake spec
