language: generic
env:
  global:
  - AWS_REGION=ap-southeast-2

sudo: required

jobs:
  include:
    - stage: deploy
      script:
      - echo "Deploying"
    - stage: test
      script:
      - bundle install
      - bundle exec rake spec

