language: generic
env:
  global:
  - AWS_REGION=ap-southeast-2

sudo: required

jobs:
  include:
    - stage: deploy
      script:
      - echo "Deploying"
      - aws cloudformation update-stack --stack-name vpc-test --template-body file://vpc.yaml
    - stage: test
      script:
      - bundle install
      - bundle exec rake spec

